-- After executing statement `CREATE DATABASE ls_burger;` and connecting to that
-- DB...

CREATE TABLE orders (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name varchar(100) NOT NULL,
  burger varchar(50),
  side varchar(50),
  drink varchar(50),
  order_total decimal(4, 2) NOT NULL
);
